# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :beta do
    sh "../build_apk.sh"
  
    firebase_app_distribution(
      app: "1:439662361776:android:1eedf6e3695a6b35c98f75",
      firebase_cli_token: "1//0eJjPVbtG22ygCgYIARAAGA4SNwF-L9IrR3SHeGbh5OFIn6q5kG2voXCuZyqPQfryBCA4kMHjUiw9XHJzknqj3ZmXpe9dr3bbetQ",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "tester"
    )
  end  
end

